"""empty message

Revision ID: a9b532e3303a
Revises: b884646117f9
Create Date: 2021-05-31 08:56:18.774362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9b532e3303a'
down_revision = 'b884646117f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('업종', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('브랜드', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('가맹점수', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('초기투자비용합계', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('예상평균매출액', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
