"""empty message

Revision ID: b884646117f9
Revises: de5d5e580b56
Create Date: 2021-05-31 08:54:58.862071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b884646117f9'
down_revision = 'de5d5e580b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('업종', sa.String(length=45), nullable=True),
    sa.Column('브랜드', sa.String(length=45), nullable=True),
    sa.Column('가맹점수', sa.Integer(), nullable=True),
    sa.Column('초기투자비용합계', sa.Integer(), nullable=True),
    sa.Column('예상평균매출액', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict')
    # ### end Alembic commands ###
