"""empty message

Revision ID: de5d5e580b56
Revises: 4011efb4df41
Create Date: 2021-05-31 08:53:33.058921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de5d5e580b56'
down_revision = '4011efb4df41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', '업종',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', '업종',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###
